name: rcc-tki-ici-wes-hla-v1-8
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas>=2.2
  - numpy>=1.26
  - scipy>=1.11
  - statsmodels>=0.14
  - lifelines>=0.30
  - matplotlib>=3.8
  - seaborn>=0.13
  - openpyxl>=3.1
  - pip
  - pip:
      - mhcflurry==2.2.1
